---
# see https://docs.mergify.com/

pull_request_rules:
  - name: "Assign PRs"
    conditions:
      - "-closed"
      - "#assignee = 0"
    actions:
      assign:
        add_users: ["{{ author }}"]

  - name: "Add label on conflicts"
    conditions:
      - "conflict"
    actions:
      comment:
        message: "@{{author}} this pull request has merge conflicts."
      label:
        add: [conflict]

  - name: "Remove label when conflicts were resolved"
    conditions:
      - "-conflict"
    actions:
      label:
        remove: [conflict]
